### ISSUE TITLE
Request to Modify Text Color for Enhanced Visibility on White Backgrounds

### ISSUE THREAD

**Issue by colesmcintosh** [het-25/st-multimodal-chatinput#1]
Hello,

Firstly, this is a fantastic component - great work! I just wanted to bring attention to a styling issue that impacts user experience, specifically regarding text visibility on white backgrounds. The current styling configuration for a component includes a text color set to white, which becomes invisible or very hard to read when placed on a light or white background in the following style:

```javascript
{
  flexGrow: 1,
  padding: "8px",
  borderRadius: "8px",
  border: "1px solid gray",
  backgroundColor: "transparent",
  resize: "none",
  overflow: "auto",
  color: "white", // Issue: Text becomes invisible on white backgrounds
  ...(isDisabled ? this.disabledStyle : {})
}
```

**Issue Description**:
The text color (`color: "white"`) specified in the style object causes the text to blend into white or light backgrounds, making it unreadable. This issue could potentially hinder accessibility and overall user experience, especially for users with visual impairments or those using themes with lighter colors.

**Suggested Change**:
I recommend removing the explicit white text color declaration or changing it to a color that ensures sufficient contrast on both light and dark backgrounds. This adjustment would significantly improve text visibility and accessibility across different themes and background colors.

Let me know what you think - Happy to help implement the change if needed. :)

**Comment by het-25** [comment]
Hi, @colesmcintosh sorry I just saw this. Do you think a color change based on the inherited background makes more sense? Or did you have another hardcoded color in mind? Would be great if you could implement a PR accordingly.

**Comment by joshuasundance-swca** [comment]
I'm not sure if this is how y'all wanna handle this, but I tested these changes: https://github.com/joshuasundance-swca/st-multimodal-chatinput/commit/31a7cb1bc25d4c18396406902bdf220e42f84c60

It just adds a `text_color` keyword argument. Inheritance may be better. I didn't update the docstring or anything, but I'd be glad to do so (and whatever else is needed) in order to make a pull request. :)

Thanks for the component!

Edit: you can test using `pip install https://github.com/joshuasundance-swca/st-multimodal-chatinput/releases/download/v0.1.7-experimental-unapproved-text-color/st_multimodal_chatinput-0.1.7-py3-none-any.whl`

The wheel comes from the `install` branch which is different from the `text-color` branch in the first link of this comment. I made the `install` branch for my own testing and development purposes, not necessarily to propose changes.

**Comment by het-25** [comment]
@joshuasundance-swca I think this actually works, maybe we can also add other styling options in the same argument because as far as I can tell, streamlit does not have explicit inheritence in components.
Can you make a pull request? I'll merge the two and push it to the main branch on pypi.
